version: "3"

tasks:
  test:
    desc: Run unit tests
    cmds:
      - go test -short -race -covermode=atomic -coverprofile=coverage.out -coverpkg=.,./storage,./test,./extensions {{ .CLI_ARGS }} ./...

  cover:
    desc: Create HTML test coverage
    cmds:
      - task: test
      - go tool cover -html coverage.out -o coverage.html

  lint:
    desc: Run linting
    cmds:
      - golangci-lint run

  gofumpt:
    desc: Run gofumpt to format
    cmd: gofumpt -w .
