// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Author struct {
	ID    string
	Name  string
	Genre string
	Bio   string
}

type Book struct {
	ID       string
	Title    string
	Isbn     string
	Year     int64
	AuthorID string
}
