name: CI

on: [push]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        run: go test -short -race -covermode=atomic -coverprofile=coverage.out -coverpkg=.,./storage ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          functionalities: "fixes"

  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build examples
        run: |
          for dir in examples/*/; do
            echo "Building $dir"
            go build $dir/*.go
          done
